name: Docker Image CI

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t jldev_jluna
    - name: Run the Docker container
      run: |
        docker run --rm -t jldev_jluna \
          -v $PWD:/workspaces -w /workspaces \
          jldev_jluna /bin/bash -c "cmake -S . -B ./build && cmake --build ./build && ./build/main"
